### PR TITLE
Upgrades component Syntax CardTabs

### PR DESCRIPTION
**Pull request by BilalBudhani**

### CODE REVIEW

**Comment by edencakir** [comment]
Is there a reason for moving this component to index.js?

Currently, components are following this format
- index.js
- component.js
- styles.js

**Comment by BilalBudhani** [comment]
@edencakir Oh, I didn't see that other components are following this as well. However, I don't see a point of having `component.js` file; If `index.js` file task is to just export whatever is in `component.js`, Yes?

**Comment by edencakir** [comment]
@BilalBudhani technically that's right, I guess Josh can answer this better @joshmadewell

**Comment by joshmadewell** [comment]
to be honest this is just a matter of preference and I've pulled it from how we build things at Twitch.

component folders should follow the following structure:

```
ComponentName
  styles.js (all the styles needed for your component)
  container.js (if your component requires redux state, wrap it in this file and export this file from index)
  component.js (the react component)
  index.js (export * from './container'/'./component';
```

Doing this just helps consolidate code into single-purpose files which improves organization.

**Comment by BilalBudhani** [comment]
@joshmadewell makes sense. I will remove my `MediaCard` related changes.

**Comment by BilalBudhani** [comment]
@joshmadewell @edencakir you guys can review this now.

**Pull request merged**
