### PR TITLE
Image uploader

### PR DESCRIPTION
**Pull request by blargity**
This component allows images to be selected from a user's camera roll or photo stream to share. Can't test on Android yet, so this is iOS only, but I figured it made more sense to merge it in and keep moving rather than block until I can test Android at this stage.

- I also added a `.editorconfig` so that anyone using Editor Config will get their editor all set up for the project automatically.
- I moved the home screen into a folder called `Activity` as either that or `Feed` will be the name for that stack. I put the component I built into that stack.
- I did not link it to Redux in any way, as the state inside this flow shouldn't need to be shared anywhere else until the post is complete, and probably then we'd just refetch from the server rather than trying to push right over to the screen via Redux

### CODE REVIEW

**Comment by BilalBudhani** [comment]
Hi, @blargity Thanks for your pull request. There has been some refactoring in the `routes` format (check #9), Basically, I broke down the routes into their respected files for sanity purpose. It would be great if you can update your PR as per that approach.

**Comment by blargity** [comment]
I think I've merged in your changes correctly. I put this component in the `PostCreation` directory but I'm not sure if that's exactly where it should go. Also the naming conventions seem different in that folder, so I'm hoping that's where this should live.

**Comment by matthewdias** [comment]
@BilalBudhani if we could match those up so they all use `PascalCase` that'd be great.

**Comment by blargity** [comment]
Can we go ahead and merge this in so we can keep moving, or do those case changes need to be wrapped into this PR?

**Comment by JoshFabian** [comment]
🚢

**Comment by JoshFabian** [comment]
🚢 - @BilalBudhani merged this to remove a blocker, when you have a moment to take care of the case changes, please do.

**Comment by BilalBudhani** [comment]
@JoshFabian Okay, I actually wanted to get some fixes done as well before merging it. But, I will take care of that in next branch.

**Pull request merged**
