### PR TITLE
WIP: Downgrades RN version to 0.46

### PR DESCRIPTION
**Pull request by edencakir**
Just updated react-native and dependencies. No need to downgrade native base.

Tested iOS and Android build, both succeeded although got few warnings at android build about missing native component. Hope Travis builds pass (btw, why don't we enable Travis to build PRs? This could prevent similar issues from happening 💃 ).

 @joshmadewell

### CODE REVIEW

**Comment by BilalBudhani** [comment]
@edencakir why are we downgrading? I thought the upgrade to `0.48` was successful.

**Comment by edencakir** [comment]
@BilalBudhani Travis builds fail due to dependency errors ( if we make android work, iOS fails and vice versa), therefore Crashlytics isn't working.

**Comment by BilalBudhani** [comment]
@edencakir is there a place where I can see error logs? I think reverting back will widen the gap between our app & react native releases.

**Comment by edencakir** [comment]
@BilalBudhani see commits section of master, there you'll see some red X marks about errors. Most of the errors are dependency linkage errors

**Comment by joshmadewell** [comment]
@BilalBudhani there are some dependencies we use that are not compatible with 0.48 on both android AND ios -- just another reason to use as few libraries as possible.

**Comment by edencakir** [comment]
#65 updated.

**Pull request closed without merging**
